### ISSUE TITLE
Script wrongly modifies '@' record for my domain

### ISSUE THREAD

**Issue by ddelhoum** [Danamir/dyn-gandi#17]
Hi,
i try to update a record in my domain, but script modifies '@' record instead, and this must not happen. If i delete '@' record in `config.ini`, i have an error : 

My config.ini : 
> cat /etc/dyn-gandi/config.ini 
> [api]
> url = https://dns.api.gandi.net/api/v5
> ; Generate your Gandi API key via : https://account.gandi.net/en/users/<user>/security
> key = secret

> [dns]
> domain = mydomain
> ; comma-separated records list
> records = myrecord
> ttl = 3600

> [ip]
> ; Choose an IP resolver : either plain text, or web page containing a single IP
> resolver_url = http://ipecho.net/plain
> ; resolver_url = http://ifconfig.me/ip
> ; resolver_url = http://www.mon-ip.fr

> ; Optional alternative IP resolver, called on timeout
> resolver_url_alt =

`/usr/local/bin/dyn_gandi -c /etc/dyn-gandi/config.ini --dry-run`

> Resolved IP: 1.2.3.4
> Domain: mydomain
> Records: myrecord/A
> 2019-10-18 14:20:22 - LiveDNS error: Main record not found to check DNS IP for domain mydomain. [ERROR]
> 2019-10-18 14:20:22 - LiveDNS error: Main record not found to check DNS IP for domain mydomain. [ERROR]

If i add @ to the record variable, there's no error but script modify my '@' record, this is not wanted.
> records = @,myrecord

`/usr/local/bin/dyn_gandi -c /etc/dyn-gandi/config.ini --dry-run`

> Resolved IP: 1.2.3.4

> Domain: mydomain

> Records: @/A, myrecord/A

> ======== Dry run ========

> Would update records:

> @/A from 10.11.12.13 to 1.2.3.4 <= **WRONG, must not modify**

> myrecord/A from None to 1.2.3.4

> =========================

> 2019-10-18 14:07:55 - Local IP: 1.2.3.4, DNS IP:10.11.12.13 [DRY RUN]

**Comment by ddelhoum** [comment]
Sorry, 
i found my mistake.
My record was a CNAME, not a A record.
Works well, now !
thanks,

**Comment by Danamir** [comment]
Glad it worked out allright ! 😄 
See ya,
