### ISSUE TITLE
Syntax to update a specific A record ?

### ISSUE THREAD

**Issue by vincegre** [Danamir/dyn-gandi#4]
Hi

I'm trying your script with my domain hosted on new V5 Gandi platform but I'm not sure syntax to use to indicate the specific A records I want to update in my domain. I don't see any examples in README neither in the config file included :(

Thanks for explanations ;)

Vincèn

**Comment by Danamir** [comment]
For my own site I use this line in `config.ini` :
```
records = @,www,ftp,ssh
```

Hope this helps !

**Comment by vincegre** [comment]
Thanks so I modified my config file but when I start the program here is what I get (I installed the script with python3 command to be sure it uses well python3 to install and setup ;)

```
root@serveur:~/dyn-gandi-master# dyn_gandi --dry-run
Traceback (most recent call last):
  File "/usr/local/bin/dyn_gandi", line 11, in <module>
    load_entry_point('dyn-gandi==1.0', 'console_scripts', 'dyn_gandi')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'dyn_gandi'
root@serveur:~/dyn-gandi-master#
```

**Comment by Danamir** [comment]
If you are using a virtual environment : have you reactivated it, or using the correct python interpreter ie. `.env/bin/python` ?

Otherwise try directly with `python3 dyn_gandi.py --dry-run` instead of calling the generated script.

**Comment by vincegre** [comment]
> Otherwise try directly with python3 dyn_gandi.py --dry-run instead of calling the generated script

Works perfect this way, thanks a lot ;)
