### ISSUE TITLE
Pretending domain name does not exist

### ISSUE THREAD

**Issue by Pyanne** [Danamir/dyn-gandi#7]
I'm unable to get the script running. It says the domain doesn't exist although it does:
[screenshoot of DNS records](https://i85.servimg.com/u/f85/18/06/28/03/screen11.png)
```
mini:dyn-gandi-1.0 cedadmin$ uname -rs
Darwin 10.8.0

mini:dyn-gandi-1.0 cedadmin$ python3 dyn_gandi.py -d
Resolved IP: 95.140.125.30
Wrote 95.140.125.30 to ip.txt file.
Domain: cirdec.com
Records: cloud/A
Requests: method=GET url=https://dns.api.gandi.net/api/v5/domains/cirdec.com headers=None json={'x-api-key': '************************', 'Accept': 'application/json'}
2019-04-11 12:54:08 - LiveDNS error: The domain cirdec.com does not exist. [ERROR]

2019-04-11 12:54:08 - LiveDNS error: The domain cirdec.com does not exist. [ERROR]
```

**Comment by pablocolson** [comment]
Same here :/

**Comment by Danamir** [comment]
Hi, this is strange, I cannot recreate this bug but your screenshot seems correct.

There was a typo in the debug line, "headers" and "json" were inverted. I pushed the correction, and added a few lines of debug, in particular the response HTTP status code is now displayed, and also an output on request timeout.

Can you try the new version, and can you also try a simple command to check if the API correctly handles the direct request : 
```shell
curl https://dns.api.gandi.net/api/v5/domains/cirdec.com -H"x-api-key: ********" -H"Accept: application/json" -v
```

**Comment by pablocolson** [comment]
`[api]
url = https://dns.api.gandi.net/api/v5
; Generate your Gandi API key via : https://account.gandi.net/en/users/<user>/security
key = XXXXXXXXXXXX (without quotes)

[dns]
domain = xx.xx.fr
; comma-separated records list
records = @,www
ttl = 3600

[ip]
; Choose an IP resolver : either plain text, or web page containing a single IP
resolver_url = http://ipecho.net/plain
; resolver_url = http://ifconfig.me/ip
; resolver_url = http://www.mon-ip.fr

; Optional alternative IP resolver, called on timeout
resolver_url_alt =`

Response is {"code": 404, "message": "The resource could not be found.", "object": "HTTPNotFound", "cause": "Not Found"}% with the curl

And the normal way
Requests: method=GET url=https://dns.api.gandi.net/api/v5/domains/xx.xx.fr headers={'Accept': 'application/json', 'x-api-key': 'XXXXXXXXXXXXX'} json=None
Response: status_code=404 ok=False

**Comment by Danamir** [comment]
The curl verbose command should display `HTTP/1.1 200 OK` in the return code.
Maybe try to generate a new API key ? 

As long as it does not work with curl, it won't work either with dyn-gandi .

**Comment by pablocolson** [comment]
In my previous answer I used a subdomain.mydomain.fr with dan-gandi and the curl line, when I use only mydomain.fr with curl I have the 200 code :) subdomain cannot be used maybe ?

**Comment by Danamir** [comment]
Yeah, the subdomain is literally defined  by your CNAME entry. ^^ The gandi API expects the base domain name in the url.

I should cleanup the subdomain just in case.

**Comment by pablocolson** [comment]
it's working now I did something like this in the config file

[dns]
domain = domain.fr
; comma-separated records list
records = subdomain,www.subdomain

not really sure for the "www.subdomain" but no error ...

**Comment by Danamir** [comment]
The `www.subdomain` is necessary only if you have a www.subdomain.domain.fr entry in your DNS. But it should not break the script if not found.

NB: I updated the script to auto clean the domain definition if needed.

**Comment by pablocolson** [comment]
works like a charm now thanks ;)

**Comment by courville** [comment]
FYI I have the same issue with current release and I had to revert back to July patch to get the script work again without a change in my configuration file.

**Comment by Adnn** [comment]
I have this issue right now (as a first time user of the script), also my configuration looks like that:

```
[dns]
domain = mydomain.fr
; comma-separated records list
records = subdomain
```

**Comment by Adnn** [comment]
@Danamir

**Comment by Danamir** [comment]
Have you a full trace to show where the bug is happening ?

**Comment by Adnn** [comment]
Thank you for your quick response!

It turns out it was a configuration problem with my (old) domain name on Gandi.
I had to follow this guideline to enable Gandi Live DNS:
https://docs.gandi.net/en/domain_names/common_operations/changing_nameservers.html#switching-to-livedns

Maybe you want to make a note of it in the main README, in case someone else encounters this issue because they never switched their old domain?

Thank you for this project!

**Comment by Danamir** [comment]
Will do.

Do you remember if the error had a specific message that I could add to the explanation ?

**Comment by Adnn** [comment]
The script error message was the same as this first post:

`error: The domain domain.fr does not exist. [ERROR]`

When running the script in debug, it seemed to be because of a 404 response on "GET url=https://dns.api.gandi.net/api/v5/domains/domain.fr" endpoint.
