### ISSUE TITLE
.co.uk domains 

### ISSUE THREAD

**Issue by kour1er** [Danamir/dyn-gandi#9]
Running into an issue with a .co.uk domain. In dyn_gandi.py line 186-189 your regex thinks that .co.uk is a subdomain. So for example if I had test.co.uk dyn_gandi.py seems to think that 'co.uk' is the domain and discards 'test'.

Thanks for the great tool btw

**Comment by Danamir** [comment]
Hello, I added a simple solution for the `.co.uk` domains, since I cant find a list of top-level domains composed of two parts. And a generic one based on the domain length could possibly have worse side effects. 

The latest release should work for your domain.

**Comment by kour1er** [comment]
Works perfectly - cheers
